name: json_god
version: 2.0.0-beta
authors:
  - Tobe O <thosakwe@gmail.com>
description: Easy JSON serialization and deserialization in Dart.
homepage: https://github.com/thosakwe/json_god
environment:
  sdk: ">=1.0.0"
dev_dependencies:
  browser: "0.10.0+2"
  test: ^0.12.13+5
