name: json_conv
version: 0.0.1
authors:
  - Kemonozume <s.kranz90@gmail.com>
description: Easy JSON serialization and deserialization in Dart.
homepage: https://github.com/Kemonozume/json_god
environment:
  sdk: ">=1.22.0"
  
dependencies:
  logging: any 

dev_dependencies:
  browser: "0.10.0+2"
  test: ^0.12.13+5
