name: json_god
version: 1.0.0-beta.4
authors:
  - Tobe O <thosakwe@gmail.com>
description: Easy JSON serialization and deserialization in Dart.
homepage: https://github.com/thosakwe/json_god
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  browser: any
