name: json_conv
version: 0.0.3
authors:
  - Kemonozume <s.kranz90@gmail.com>
description: Easy JSON serialization and deserialization in Dart.
homepage: https://github.com/Kemonozume/json_god
environment:
  sdk: ">=1.22.1"
  
dependencies:
  logging: any 

dev_dependencies:
  test: ^0.12.13+5
